@WebApiPatchPoC_HostAddress = http://localhost:5006

### Get all products
GET {{WebApiPatchPoC_HostAddress}}/api/products
Accept: application/json

### Get product by SKU - Success
GET {{WebApiPatchPoC_HostAddress}}/api/products/PC-MOUSE-001
Accept: application/json

### Get product by SKU - Not Found
GET {{WebApiPatchPoC_HostAddress}}/api/products/INVALID-SKU
Accept: application/json

### Get product by SKU - Invalid Format (should fail validation)
GET {{WebApiPatchPoC_HostAddress}}/api/products/INVALID-SKÙ
Accept: application/json

###
